# Generated by Django 3.2.9 on 2021-11-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mom_classification', models.CharField(choices=[('XXXXX', 'Known Wizard  Killer'), ('XXXX', 'Dangerous'), ('XXX', 'Competent wizard should cope'), ('XX', 'Harmless'), ('X', 'Boring')], max_length=5)),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='beast')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('total_pages', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=5)),
                ('photo', models.ImageField(upload_to='uploads')),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
