# Generated by Django 3.2.9 on 2021-11-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_beast_book_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beast',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
