# Generated by Django 3.2.9 on 2021-11-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211124_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
